services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: success-academy-web
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/success_academy?ssl=false
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - ./uploads:/app/uploads
      - /app/node_modules        # ensure container’s node_modules isn’t overwritten
    command: ["npm", "run", "dev"]  # use Next’s dev server
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: success-academy-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: success_academy
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d success_academy"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
